# Generated by Django 3.2 on 2021-05-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210509_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.IntegerField(),
        ),
    ]
