# Generated by Django 3.2 on 2021-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='baseprice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
