# Generated by Django 3.2 on 2021-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='baseprice',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Auction'),
        ),
    ]
