# Generated by Django 3.2 on 2021-05-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210515_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_auction', to='auctions.bid'),
        ),
    ]
