# Generated by Django 3.2 on 2021-05-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='baseprice',
        ),
    ]
