# Generated by Django 3.2 on 2021-05-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_auction_baseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_auction', to='auctions.bid', verbose_name='bid'),
        ),
    ]
