# Generated by Django 3.2 on 2021-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210517_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('value', 'auction')},
        ),
    ]
