# Generated by Django 3.2 on 2021-05-18 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210518_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 16, 29, 37, 70806)),
        ),
    ]
